### ISSUE TITLE
Impossible to mint large amount

### ISSUE THREAD

**Issue by PhilippeR26** [0xSpaceShard/starknet-devnet-js#10]
I think I discovered a problem with the mint method.
If I try to mint 100 STRK this way :
```typescript
l2DevnetProvider.mint(accountBraavosAddress, 100 * 10 ** 18, "FRI");
```
The console display :
```
ERROR rpc: failed to deserialize method method="devnet_mint" err="invalid digit found in string"
```
Same with "WEI". Works with 10 *10**18.
Probably the fact that `amount` parameter should be a bigint to handle large numbers.
### Config : 
- devnet-rs v0.1.1
- starknet-devnet.js v0.0.4

**Comment by FabijanC** [comment]
Is this a blocker for you? Or did you just run across this while experimenting with values? For now I can recommend minting several times in a row with smaller values (not ideal, I know).

The problem is also on the server side: https://github.com/0xSpaceShard/starknet-devnet-rs/issues/533

## Temporary solution:
Change `number` to `bigint` and use `POST /mint` as the underlying mechanism instead of `JSON-RPC devnet_mint`
